# Development Dockerfile for Rails application
# This is optimized for development with live code reloading

ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    libpq-dev \
    libyaml-dev \
    pkg-config \
    postgresql-client \
    vim \
    nodejs \
    npm \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Set working directory
WORKDIR /rails

# Set development environment
ENV RAILS_ENV=development \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="" \
    RAILS_LOG_TO_STDOUT=true

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Add entrypoint scripts
COPY entrypoint.dev.sh /usr/bin/
# COPY entrypoint.vite.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.dev.sh /usr/bin/entrypoint.vite.sh
RUN chmod +x /usr/bin/entrypoint.dev.sh
ENTRYPOINT [ "entrypoint.dev.sh" ]

# Configure the main process to run when running the image
# EXPOSE 3000 3036 3001 9222
EXPOSE 3000

# Start the main process
CMD ["rails", "server", "-b", "0.0.0.0"] 